name: React Native Build and Test

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Jest and React Native Testing Libraries
        run: |
          npm install jest @testing-library/react-native jest-react-native babel-jest react-test-renderer --save-dev

      - name: Add Jest configuration to package.json
        run: |
          jq '.jest = {
            "preset": "react-native",
            "setupFilesAfterEnv": ["@testing-library/jest-native/extend-expect"],
            "transformIgnorePatterns": [
              "node_modules/(?!(react-native|my-project|react-native-button)/)"
            ]
          }' package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Add Jest test script
        run: |
          jq '.scripts.test="jest"' package.json > package.tmp.json && mv package.tmp.json package.json

      - name: Run tests
        run: npm test
